### PR TITLE
Adds promise support. Fixes #26

### LINKED ISSUE #26: Promise support
Hi, as async/await support is widespread now, it would be great to have out-of-the box promise support  in this great lib. Do you plan implementing it?

### PR DESCRIPTION
**Pull request by gyszalai**
Created a very simple wrapper function for promise support.

### CODE REVIEW

**Comment by jeffbski** [comment]
awesome! I'll review and get it merged.

**Comment by gyszalai** [comment]
any update on this?

**Comment by jeffbski** [comment]
Fantastic PR! thanks @gyszalai

**Comment by jeffbski** [comment]
Landed in v3.1.0

**Comment by gyszalai** [comment]
Thanks for merging! 🤓

**Pull request merged**
