### PR TITLE
Pass through options for http

### LINKED ISSUE #2: Waiting on an https resource that uses self-signed certs

### LINKED ISSUE #4: Allow passing HTTP authentication options

### PR DESCRIPTION
**Pull request by lumberj**
This would allow passing through options for http authentication and TLS

Fixes #4

### CODE REVIEW

**Comment by lumberj** [comment]
Thanks for the quick turnaround @jeffbski, will you be doing a release with this feature?

**Comment by jeffbski** [comment]
Yes, I am adding some documentation for the change and then will release a
new minor version.

On Thu, Mar 3, 2016 at 2:39 PM, Alan Cohen <notifications@github.com> wrote:

> Thanks for the quick turnaround @jeffbski <https://github.com/jeffbski>,
> will you be doing a release with this feature?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeffbski/wait-on/pull/3#issuecomment-191952457>.
>



-- 
Jeff Barczewski
Founder of CodeWinds
http://codewinds.com/
Web developer training - screencasts, podcast, blog

**Comment by lumberj** [comment]
I noticed that I should also add the options to the CLI

**Comment by jeffbski** [comment]
Yeah, that would be great. I'm thinking maybe if we added a cli option to
specify a config.js or config.json file then we could read that in to get
the options which would be too verbose to specify in the cli.

What do you think?

On Thu, Mar 3, 2016 at 2:41 PM, Alan Cohen <notifications@github.com> wrote:

> I noticed that I should also add the options to the CLI
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeffbski/wait-on/pull/3#issuecomment-191953171>.
>



-- 
Jeff Barczewski
Founder of CodeWinds
http://codewinds.com/
Web developer training - screencasts, podcast, blog

**Comment by lumberj** [comment]
I like the idea of using a config file, as some of the options are specified as JSON objects (http basic-auth for example, `{auth: {username: '', password: ''}}`.

**Comment by jeffbski** [comment]
published to npm in version 1.4.0

**Pull request merged**
