### PR TITLE
`ignoreProxy` for axios request

### PR DESCRIPTION
**Pull request by kspramod**
set `proxy: false` for axios config to handle proxy enabled systems, handle `proxy` system when `http_proxy` variables are set.
https://github.com/axios/axios/issues/1514#issuecomment-392650702

### CODE REVIEW

**Comment by jeffbski** [comment]
@kspramod Thanks for the PR. I agree we need to have a way to override the env vars if they are set. 

Your change would be fine if we only ever wanted to just disable, but if we actually need to override to a different proxy value (like providing host, etc) then maybe it would be better to just allow an optional `proxy` variable that gets passed through as is to axios. That way it would support the full range of settings allowed by axios. 

I'll put a RC up for you to try out. You would simply provide `proxy: false`  to the wait-on config for your use case.

**Comment by jeffbski** [comment]
@kspramod I have published a release candidate with the `proxy` option. 

npm i wait-on@5.1.0-rc.0

You would provide `proxy: false` as the config to override the use of env vars. 

Let me know if this works for you and we can publish it as a release.

**Comment by kspramod** [comment]
@jeffbski thanks for looking into that. Yup I should have provided `proxy` config option my bad.
Anyways, current changes work but need minor fix.
`...(proxy || proxy === false && { proxy }),` as `proxy` can be falsy value need an explicit condition. Also checked with proxy hostname and port and works fine 👍

**Comment by jeffbski** [comment]
Good catch @kspramod I will update this and put a new RC out there to test

**Comment by jeffbski** [comment]
@kspramod ok, I published 5.1.0-rc.1 if you would give it a try and make sure it works.

**Comment by kspramod** [comment]
@jeffbski thanks 👍 
that works for all scenarios, with proxy host and port, no proxy and proxy as false 👍

**Comment by jeffbski** [comment]
@kspramod Thanks for submitting this and working with me to test it. I have published the release 5.1.0 with this change in it. https://github.com/jeffbski/wait-on/releases/tag/v5.1.0

**Pull request closed without merging**
